[package]
name = "wiki_comments"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.10.2"
diesel = {version = "2.2.0", features = ["postgres"]}
dotenvy = "0.15"
serde = {version = "1.0.219", features = ["derive"]}

